project_id = "wqygamcvraihqsslowhs"

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-assessment-invitation]
verify_jwt = true

[functions.regenerate-pdf]
verify_jwt = true